name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: obot
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get install libpq-dev -y
        cargo install sqlx-cli

    - name: Run Migrations
      run: |
        sqlx database create
        sqlx migrate run

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release
