name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: obot
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Cache Cargo Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Dependencies
      run: |
        if ! command -v sqlx > /dev/null; then
          sudo apt-get install libssl-dev -y
          cargo install sqlx-cli
        fi

    - name: Run Migrations
      run: |
        sqlx database create
        sqlx migrate run

    - name: Check
      run: cargo check --release

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release
